version: "3.8"
volumes:
  web_data:
#  node_modules:
services:
  app:
    image: node:14
    volumes:
      - .:/app
#      - node_modules:/app/node_modules
      - web_data:/dist:rw
    command: /bin/bash -c './run-integration-tests.sh'
    working_dir: /app
    environment:
      - CYPRESS_INSTALL_BINARY="0"
      - LIB_NAME="crossref-ui"
      - CI_PIPELINE_ID
    ports:
    - 8080:80
    - 3000:3000
  web:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - web_data:/usr/share/nginx/html:ro
  frontend-e2e-test:
    image: cypress/included:6.5.0
    volumes:
      - .:/e2e
#      - /e2e/node_modules
    entrypoint: ''
    working_dir: /e2e
    command: /bin/bash -c 'npx wait-on -l http-get://app:3000/echo && cypress run --spec cypress/integration/auth_spec.js'
